const mapping={TA:[{hand:"R"}],THAKA:[{hand:"R"},{hand:"L"}],THAKKA:[{hand:"R",accent:true},{hand:"L"}],THAKITA:[{hand:"R"},{hand:"R"},{hand:"L"}]};
const wordColors={TA:{fill:"#f2b94b",glow:"rgba(242,185,75,.72)",text:"#090a0e"},THAKA:{fill:"#42c8c8",glow:"rgba(66,200,200,.72)",text:"#071011"},THAKITA:{fill:"#8d7cff",glow:"rgba(141,124,255,.74)",text:"#090a0e"},THAKKA:{fill:"#e95a45",glow:"rgba(233,90,69,.78)",text:"#fff8ec"}};
const $=id=>document.getElementById(id);
const app=$("app"),canvas=$("lane"),ctx=canvas.getContext("2d"),patternInput=$("patternInput"),warning=$("warning"),bpm=$("bpm"),bpmNumber=$("bpmNumber"),startBtn=$("start"),stopBtn=$("stop"),restartBtn=$("restart"),fullscreenBtn=$("fullscreen"),fullscreenStopBtn=$("fullscreenStop"),fullscreenRestartBtn=$("fullscreenRestart"),exitFullscreenBtn=$("exitFullscreen"),savePatternBtn=$("savePattern"),loadPatternBtn=$("loadPattern"),deletePatternBtn=$("deletePattern"),savedPatternsSelect=$("savedPatterns"),compactToggle=$("compactToggle"),stateEl=$("state"),wordCountEl=$("wordCount"),hitCountEl=$("hitCount"),nowWordEl=$("nowWord");
let baseWords=[],words=[],hits=[],groups=[],running=false,startTime=0,pauseElapsed=0,raf=0,loopCount=1,totalBeats=0,compactLanes=true;const countInBeats=4,prepGapBeats=1,hitFadeBeats=.34;
const patternLibraryKey="chendaPracticePatterns";
function readPatternLibrary(){try{const raw=localStorage.getItem(patternLibraryKey);const parsed=raw?JSON.parse(raw):{};return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{}}catch(error){return {}}}
function writePatternLibrary(library){localStorage.setItem(patternLibraryKey,JSON.stringify(library))}
function refreshSavedPatterns(selectedName=""){const library=readPatternLibrary();const names=Object.keys(library).sort((a,b)=>a.localeCompare(b));savedPatternsSelect.innerHTML="";const empty=document.createElement("option");empty.value="";empty.textContent=names.length?"Choose a saved pattern":"No saved patterns";savedPatternsSelect.appendChild(empty);names.forEach(name=>{const option=document.createElement("option");option.value=name;option.textContent=name;savedPatternsSelect.appendChild(option)});if(selectedName&&library[selectedName])savedPatternsSelect.value=selectedName}
function saveCurrentPattern(){const current=patternInput.value.trim();if(!current){window.alert("Enter a pattern before saving.");return}const name=(window.prompt("Pattern name",savedPatternsSelect.value||"")||"").trim();if(!name)return;const library=readPatternLibrary();library[name]=patternInput.value;writePatternLibrary(library);refreshSavedPatterns(name)}
function loadSelectedPattern(){const name=savedPatternsSelect.value;if(!name)return;const library=readPatternLibrary();if(!library[name])return;const was=running;if(was)stopReference();patternInput.value=library[name];parsePattern();pauseElapsed=0;draw(0)}
function deleteSelectedPattern(){const name=savedPatternsSelect.value;if(!name)return;const library=readPatternLibrary();if(!library[name])return;if(!window.confirm("Delete saved pattern: "+name+"?"))return;delete library[name];writePatternLibrary(library);refreshSavedPatterns()}

function resizeCanvas(){const rect=canvas.getBoundingClientRect();const ratio=Math.min(window.devicePixelRatio||1,2);const width=Math.max(320,Math.round(rect.width*ratio));const height=Math.max(340,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}}
function beatMs(){return 60000/Number(bpm.value)}
function clampBpm(value){const parsed=Number(value);if(!Number.isFinite(parsed))return Number(bpm.value)||96;return Math.max(100,Math.min(500,Math.round(parsed)))}
function applyBpm(value,{restart=false}={}){const next=clampBpm(value);bpm.value=String(next);bpmNumber.value=String(next);const was=running;if(restart&&was)stopReference();parsePattern();if(restart&&was)startReference();else draw(pauseElapsed)}
function parsePattern(){const raw=patternInput.value.toUpperCase().match(/[A-Z]+/g)||[];const bad=[];baseWords=[];raw.forEach(word=>mapping[word]?baseWords.push(word):bad.push(word));if(!baseWords.length)baseWords=["TA"];warning.textContent=bad.length?"Ignored: "+[...new Set(bad)].join(", "):"";words=[];for(let i=0;i<loopCount;i++)words.push(...baseWords);buildTimeline();updateInfo(0)}
function buildTimeline(){hits=[];groups=[];let beat=countInBeats+prepGapBeats;words.forEach((word,index)=>{const parts=mapping[word];const startBeat=beat;parts.forEach((part,offset)=>{hits.push({hand:part.hand,accent:!!part.accent,word,wordIndex:index,part:offset,timeBeat:beat+offset})});groups.push({word,index,startBeat,endBeat:startBeat+parts.length-1,centerBeat:startBeat+(parts.length-1)/2});beat+=parts.length});totalBeats=beat}
function updateInfo(now){wordCountEl.textContent=words.length;hitCountEl.textContent=hits.length;const b=now/beatMs();if(b<countInBeats){nowWordEl.textContent=String(Math.min(4,Math.floor(b)+1));return}if(b<countInBeats+prepGapBeats){nowWordEl.textContent="Ready";return}const active=groups.find(g=>b>=g.startBeat-.22&&b<=g.endBeat+.22);nowWordEl.textContent=active?active.word:"-"}
function resetReference(){parsePattern();pauseElapsed=0;startTime=performance.now();draw(0)}
function startReference(){if(running)return;running=true;app.classList.add("playing");stateEl.textContent="Count-in";startTime=performance.now()-pauseElapsed;loop()}
function stopReference(){if(!running)return;running=false;pauseElapsed=performance.now()-startTime;app.classList.remove("playing");stateEl.textContent="Stopped";cancelAnimationFrame(raf);draw(pauseElapsed)}
function finishReference(now){running=false;pauseElapsed=now;app.classList.remove("playing");stateEl.textContent="Stopped";cancelAnimationFrame(raf);draw(now);updateInfo(now)}
function restartReference(){running=false;cancelAnimationFrame(raf);parsePattern();pauseElapsed=0;startReference()}
function elapsed(){return running?performance.now()-startTime:pauseElapsed}
function loop(){const now=elapsed();const b=now/beatMs();stateEl.textContent=b<countInBeats?"Count-in":"Playing";draw(now);updateInfo(now);if(b>totalBeats+1.15){finishReference(now);return}if(running)raf=requestAnimationFrame(loop)}
function draw(now){resizeCanvas();const w=canvas.width,h=canvas.height;const hitY=h-112;const topPad=84;const leadBeats=8;const msPerBeat=beatMs();const laneW=compactLanes?Math.min(150,w*.22):Math.min(230,w*.3);const gap=compactLanes?Math.max(6,Math.min(10,w*.018)):Math.min(60,w*.08);const leftX=w/2-laneW/2-gap/2;const rightX=w/2+laneW/2+gap/2;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#151923");bg.addColorStop(1,"#08090d");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);drawLane(leftX,laneW,"Left hand lane","#42c8c8");drawLane(rightX,laneW,"Right hand lane","#f2b94b");drawDivider(leftX,rightX);ctx.strokeStyle="#fff1a0";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(leftX-laneW/2-16,hitY);ctx.lineTo(rightX+laneW/2+16,hitY);ctx.stroke();ctx.fillStyle="rgba(242,185,75,.18)";ctx.fillRect(leftX-laneW/2-16,hitY-15,rightX-leftX+laneW+32,30);const nowBeat=now/msPerBeat;drawCountIn(nowBeat,w,h,hitY);groups.forEach(group=>{const y=hitY-(group.centerBeat-nowBeat)/leadBeats*(hitY-topPad);if(y<-54||y>h+46)return;const parts=mapping[group.word];const x1=laneXForHand(parts[0].hand,leftX,rightX);const x2=laneXForHand(parts[parts.length-1].hand,leftX,rightX);ctx.save();ctx.globalAlpha=.9;ctx.fillStyle="rgba(255,248,236,.82)";ctx.font="900 16px Inter, system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(group.word,(x1+x2)/2,y-42);ctx.restore()});hits.forEach(hit=>{const delta=nowBeat-hit.timeBeat;if(delta>hitFadeBeats)return;const y=delta>=0?hitY:hitY-(hit.timeBeat-nowBeat)/leadBeats*(hitY-topPad);if(y<-60||y>h+70)return;drawNote(laneXForHand(hit.hand,leftX,rightX),y,hit,delta)});ctx.fillStyle="rgba(255,248,236,.72)";ctx.font="800 17px Inter, system-ui";ctx.textAlign="left";ctx.fillText("BPM "+bpm.value,24,34);ctx.fillText("Loop x"+loopCount,24,58);ctx.fillText(compactLanes?"Compact lanes":"Wide lanes",24,82);const next=hits.find(hit=>hit.timeBeat>=nowBeat-.05);ctx.fillText(next?"Next: "+next.word+" "+next.hand:"Pattern complete",24,106)}
function drawCountIn(nowBeat,w,h,hitY){if(nowBeat>=countInBeats)return;const count=Math.floor(nowBeat)+1;const progress=nowBeat-Math.floor(nowBeat);ctx.save();ctx.globalAlpha=.95-progress*.2;ctx.fillStyle="rgba(255,248,236,.12)";ctx.beginPath();ctx.arc(w/2,hitY-156,70+progress*18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff8ec";ctx.font="950 84px Inter, system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(count),w/2,hitY-158);ctx.font="850 16px Inter, system-ui";ctx.fillStyle="rgba(255,248,236,.72)";ctx.fillText("count-in",w/2,hitY-98);ctx.restore()}
function drawLane(x,laneW,label,color){ctx.fillStyle="rgba(255,255,255,.055)";ctx.fillRect(x-laneW/2,0,laneW,canvas.height);ctx.strokeStyle="rgba(255,255,255,.18)";ctx.lineWidth=2;ctx.strokeRect(x-laneW/2,0,laneW,canvas.height);ctx.fillStyle=color;ctx.font="900 20px Inter, system-ui";ctx.textAlign="center";ctx.textBaseline="top";ctx.fillText(label,x,18);ctx.fillStyle="rgba(255,255,255,.045)";for(let y=74;y<canvas.height;y+=40)ctx.fillRect(x-laneW/2,y,laneW,1)}
function drawDivider(leftX,rightX){const x=(leftX+rightX)/2;ctx.save();ctx.strokeStyle="rgba(255,248,236,.38)";ctx.lineWidth=1;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function laneXForHand(hand,leftX,rightX){return hand==="R"?rightX:leftX}
function drawNote(x,y,hit,delta=-1){const palette=wordColors[hit.word]||wordColors.TA;const hitting=delta>=0;const progress=hitting?Math.min(1,delta/hitFadeBeats):0;const scale=hitting?1.08-progress*.08:1;const alpha=hitting?1-progress:.98;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.globalAlpha=alpha;ctx.shadowBlur=hitting?30-progress*12:22;ctx.shadowColor=palette.glow;ctx.fillStyle=palette.fill;const noteW=Math.max(72,Math.min(104,canvas.width*.14));const noteH=Math.max(50,Math.min(60,canvas.height*.11));roundRect(-noteW/2,-noteH/2,noteW,noteH,10);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=hitting?"#fff8ec":"rgba(255,248,236,.86)";ctx.lineWidth=hit.accent?4:3;roundRect(-noteW/2,-noteH/2,noteW,noteH,10);ctx.stroke();ctx.fillStyle=palette.text;ctx.font="950 34px Inter, system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(hit.hand,0,-2);ctx.fillStyle=hit.word==="THAKKA"?"rgba(255,248,236,.82)":"rgba(9,10,14,.72)";ctx.font="850 10px Inter, system-ui";ctx.fillText(hit.word,0,noteH*.34);ctx.fillStyle="rgba(255,248,236,.9)";ctx.beginPath();ctx.arc(0,0,4,0,Math.PI*2);ctx.fill();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function setLoop(value){loopCount=value;document.querySelectorAll(".loop").forEach(button=>button.classList.toggle("active",Number(button.dataset.loop)===loopCount));const was=running;if(was)stopReference();parsePattern();pauseElapsed=0;draw(0);if(was)startReference()}
function insertWord(word){const start=patternInput.selectionStart??patternInput.value.length;const end=patternInput.selectionEnd??start;const before=patternInput.value.slice(0,start);const after=patternInput.value.slice(end);const prefix=before&&!/\s$/.test(before)?" ":"";const insert=prefix+word+" ";patternInput.value=before+insert+after;const pos=(before+insert).length;patternInput.setSelectionRange(pos,pos);const was=running;if(was)stopReference();parsePattern();pauseElapsed=0;draw(0)}
function toggleCompact(){compactLanes=!compactLanes;compactToggle.textContent=compactLanes?"Compact lanes: ON":"Compact lanes: OFF";compactToggle.classList.toggle("active",compactLanes);draw(elapsed())}
function setFullscreenMode(active){app.classList.toggle("practiceFullscreen",active);fullscreenBtn.textContent=active?"Fullscreen: ON":"Fullscreen";setTimeout(()=>draw(elapsed()),60)}
async function enterPracticeFullscreen(){setFullscreenMode(true);try{if(!document.fullscreenElement&&app.requestFullscreen)await app.requestFullscreen()}catch(error){}draw(elapsed())}
async function exitPracticeFullscreen(){try{if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen()}catch(error){}setFullscreenMode(false)}
function syncFullscreenState(){if(!document.fullscreenElement&&app.classList.contains("practiceFullscreen"))setFullscreenMode(false)}

bpm.addEventListener("input",()=>applyBpm(bpm.value,{restart:true}));
bpmNumber.addEventListener("input",()=>{bpm.value=String(clampBpm(bpmNumber.value));draw(pauseElapsed)});
bpmNumber.addEventListener("change",()=>applyBpm(bpmNumber.value,{restart:true}));
bpmNumber.addEventListener("blur",()=>applyBpm(bpmNumber.value,{restart:true}));
patternInput.addEventListener("input",()=>{const was=running;if(was)stopReference();parsePattern();pauseElapsed=0;draw(0)});
document.querySelectorAll(".loop").forEach(button=>button.addEventListener("click",()=>setLoop(Number(button.dataset.loop))));
document.querySelectorAll(".wordButton").forEach(button=>{button.addEventListener("pointerdown",event=>event.preventDefault());button.addEventListener("click",()=>insertWord(button.dataset.insert))});
compactToggle.addEventListener("click",toggleCompact);
savePatternBtn.addEventListener("click",saveCurrentPattern);
loadPatternBtn.addEventListener("click",loadSelectedPattern);
deletePatternBtn.addEventListener("click",deleteSelectedPattern);
fullscreenBtn.addEventListener("click",enterPracticeFullscreen);
fullscreenStopBtn.addEventListener("click",stopReference);
fullscreenRestartBtn.addEventListener("click",restartReference);
exitFullscreenBtn.addEventListener("click",exitPracticeFullscreen);
document.addEventListener("fullscreenchange",syncFullscreenState);
window.addEventListener("resize",()=>draw(elapsed()));
window.addEventListener("orientationchange",()=>setTimeout(()=>draw(elapsed()),120));
startBtn.addEventListener("click",startReference);stopBtn.addEventListener("click",stopReference);restartBtn.addEventListener("click",restartReference);
refreshSavedPatterns();
resetReference();
